import './globals.css';

type PropsT = {
    children: React.ReactNode;
};

export default function RootLayout(props: PropsT) {
    const { children } = props;

    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
