import { PropsWithChildren } from 'react';
import { ThemeProvider } from 'presentation/context/Theme';
import ContextComposer from 'presentation/context/ContextComposer';
import Layout from 'presentation/component/layout';

const APP_PROVIDERS = [ThemeProvider];

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren) {
    const { children } = props;

    return (
        <html lang="en">
            <body>
                <ContextComposer components={APP_PROVIDERS}>
                    <Layout>{children}</Layout>
                </ContextComposer>
            </body>
        </html>
    );
}
